#!/bin/bash
#*++*H*++*A*++*C*++*K*++*
#*++**+T+**++*H*++**+E+**
#+ P*+ L*+ A*+ N*+ E*+ T*
#
#HACK
#THE
#PL
#This Program Runs Maltrieve & Calculates How Many Viruses
#Are Downloaded & Sorted By Type Using maltrievecategorizer
#and Then Provides a Count for Each particular Type of File

#Total Virus Count Before Running Maltrieve...

VariaVirus=$(ls /opt/maltrieve/archive | wc -l)

#Total Specific Virus Counts Before Maltrieve (By Type and Size)

#7zip Pre-Count

Szip4=$(ls /opt/maltrieve/archive/7-zip/xlarge | wc -l)
Szip3=$(ls /opt/maltrieve/archive/7-zip/large | wc -l)
Szip2=$(ls /opt/maltrieve/archive/7-zip/medium | wc -l)
Szip1=$(ls /opt/maltrieve/archive/7-zip/small | wc -l)

#ASCII Pre-Count

ASCII4=$(ls /opt/maltrieve/archive/ASCII/xlarge | wc -l)
ASCII3=$(ls /opt/maltrieve/archive/ASCII/large | wc -l)
ASCII2=$(ls /opt/maltrieve/archive/ASCII/medium | wc -l)
ASCII1=$(ls /opt/maltrieve/archive/ASCII/small | wc -l)

#BitTorrent Pre-Count

BitTorrent4=$(ls /opt/maltrieve/archive/BitTorrent/xlarge | wc -l)
BitTorrent3=$(ls /opt/maltrieve/archive/BitTorrent/large | wc -l)
BitTorrent2=$(ls /opt/maltrieve/archive/BitTorrent/medium | wc -l)
BitTorrent1=$(ls /opt/maltrieve/archive/BitTorrent/small | wc -l)

#bzip2 Pre-Count

bzip24=$(ls /opt/maltrieve/archive/bzip2/xlarge | wc -l)
bzip23=$(ls /opt/maltrieve/archive/bzip2/large | wc -l)
bzip22=$(ls /opt/maltrieve/archive/bzip2/medium | wc -l)
bzip21=$(ls /opt/maltrieve/archive/bzip2/small | wc -l)

#compiled Pre-Count

compiled4=$(ls /opt/maltrieve/archive/compiled/xlarge | wc -l)
compiled3=$(ls /opt/maltrieve/archive/compiled/large | wc -l)
compiled2=$(ls /opt/maltrieve/archive/compiled/medium | wc -l)
compiled1=$(ls /opt/maltrieve/archive/compiled/small | wc -l)

#Composite Pre-Count

Composite4=$(ls /opt/maltrieve/archive/Composite/xlarge | wc -l)
Composite3=$(ls /opt/maltrieve/archive/Composite/large | wc -l)
Composite2=$(ls /opt/maltrieve/archive/Composite/medium | wc -l)
Composite1=$(ls /opt/maltrieve/archive/Composite/small | wc -l)

#data Pre-Count

data4=$(ls /opt/maltrieve/archive/data/xlarge | wc -l)
data3=$(ls /opt/maltrieve/archive/data/large | wc -l)
data2=$(ls /opt/maltrieve/archive/data/medium | wc -l)
data1=$(ls /opt/maltrieve/archive/data/small | wc -l)

#Debian Pre-Count

Debian4=$(ls /opt/maltrieve/archive/Debian/xlarge | wc -l)
Debian3=$(ls /opt/maltrieve/archive/Debian/large | wc -l)
Debian2=$(ls /opt/maltrieve/archive/Debian/medium | wc -l)
Debian1=$(ls /opt/maltrieve/archive/Debian/small | wc -l)

#Dyalog Pre-Count

Dyalog4=$(ls /opt/maltrieve/archive/Dyalog/xlarge | wc -l)
Dyalog3=$(ls /opt/maltrieve/archive/Dyalog/large | wc -l)
Dyalog2=$(ls /opt/maltrieve/archive/Dyalog/medium | wc -l)
Dyalog1=$(ls /opt/maltrieve/archive/Dyalog/small | wc -l)

#ELF Pre-Count

ELF4=$(ls /opt/maltrieve/archive/ELF/xlarge | wc -l)
ELF3=$(ls /opt/maltrieve/archive/ELF/large | wc -l)
ELF2=$(ls /opt/maltrieve/archive/ELF/medium | wc -l)
ELF1=$(ls /opt/maltrieve/archive/ELF/small | wc -l)

#Emacs Pre-Count

Emacs4=$(ls /opt/maltrieve/archive/Emacs/xlarge | wc -l)
Emacs3=$(ls /opt/maltrieve/archive/Emacs/large | wc -l)
Emacs2=$(ls /opt/maltrieve/archive/Emacs/medium | wc -l)
Emacs1=$(ls /opt/maltrieve/archive/Emacs/small | wc -l)

#exported Pre-Count

exported4=$(ls /opt/maltrieve/archive/exported/xlarge | wc -l)
exported3=$(ls /opt/maltrieve/archive/exported/large | wc -l)
exported2=$(ls /opt/maltrieve/archive/exported/medium | wc -l)
exported1=$(ls /opt/maltrieve/archive/exported/small | wc -l)

#GIF Pre-Count

GIF4=$(ls /opt/maltrieve/archive/GIF/xlarge | wc -l)
GIF3=$(ls /opt/maltrieve/archive/GIF/large | wc -l)
GIF2=$(ls /opt/maltrieve/archive/GIF/medium | wc -l)
GIF1=$(ls /opt/maltrieve/archive/GIF/small | wc -l)

#HTML Pre-Count

HTML4=$(ls /opt/maltrieve/archive/HTML/xlarge | wc -l)
HTML3=$(ls /opt/maltrieve/archive/HTML/large | wc -l)
HTML2=$(ls /opt/maltrieve/archive/HTML/medium | wc -l)
HTML1=$(ls /opt/maltrieve/archive/HTML/small | wc -l)

#ISO Pre-Count

ISO4=$(ls /opt/maltrieve/archive/ISO/xlarge | wc -l)
ISO3=$(ls /opt/maltrieve/archive/ISO/large | wc -l)
ISO2=$(ls /opt/maltrieve/archive/ISO/medium | wc -l)
ISO1=$(ls /opt/maltrieve/archive/ISO/small | wc -l)

#ISO8859 Pre-Count

ISO88594=$(ls /opt/maltrieve/archive/ISO-8859/xlarge | wc -l)
ISO88593=$(ls /opt/maltrieve/archive/ISO-8859/large | wc -l)
ISO88592=$(ls /opt/maltrieve/archive/ISO-8859/medium | wc -l)
ISO88591=$(ls /opt/maltrieve/archive/ISO-8859/small | wc -l)

#Java Pre-Count

Java4=$(ls /opt/maltrieve/archive/Java/xlarge | wc -l)
Java3=$(ls /opt/maltrieve/archive/Java/large | wc -l)
Java2=$(ls /opt/maltrieve/archive/Java/medium | wc -l)
Java1=$(ls /opt/maltrieve/archive/Java/small | wc -l)

#JPEG Pre-Count

JPEG4=$(ls /opt/maltrieve/archive/JPEG/xlarge | wc -l)
JPEG3=$(ls /opt/maltrieve/archive/JPEG/large | wc -l)
JPEG2=$(ls /opt/maltrieve/archive/JPEG/medium | wc -l)
JPEG1=$(ls /opt/maltrieve/archive/JPEG/small | wc -l)

#Lha Pre-Count

Lha4=$(ls /opt/maltrieve/archive/Lha/xlarge | wc -l)
Lha3=$(ls /opt/maltrieve/archive/Lha/large | wc -l)
Lha2=$(ls /opt/maltrieve/archive/Lha/medium | wc -l)
Lha1=$(ls /opt/maltrieve/archive/Lha/small | wc -l)

#Littleendian Pre-Count

Littleendian4=$(ls /opt/maltrieve/archive/Littleendian/xlarge | wc -l)
Littleendian3=$(ls /opt/maltrieve/archive/Littleendian/large | wc -l)
Littleendian2=$(ls /opt/maltrieve/archive/Littleendian/medium | wc -l)
Littleendian1=$(ls /opt/maltrieve/archive/Littleendian/small | wc -l)

#Macintosh Pre-Count

Macintosh4=$(ls /opt/maltrieve/archive/Macintosh/xlarge | wc -l)
Macintosh3=$(ls /opt/maltrieve/archive/Macintosh/large | wc -l)
Macintosh2=$(ls /opt/maltrieve/archive/Macintosh/medium | wc -l)
Macintosh1=$(ls /opt/maltrieve/archive/Macintosh/small | wc -l)

#Macromedia Pre-Count

Macromedia4=$(ls /opt/maltrieve/archive/Macromedia/xlarge | wc -l)
Macromedia3=$(ls /opt/maltrieve/archive/Macromedia/large | wc -l)
Macromedia2=$(ls /opt/maltrieve/archive/Macromedia/medium | wc -l)
Macromedia1=$(ls /opt/maltrieve/archive/Macromedia/small | wc -l)

#Microsoft Pre-Count

Microsoft4=$(ls /opt/maltrieve/archive/Microsoft/xlarge | wc -l)
Microsoft3=$(ls /opt/maltrieve/archive/Microsoft/large | wc -l)
Microsoft2=$(ls /opt/maltrieve/archive/Microsoft/medium | wc -l)
Microsoft1=$(ls /opt/maltrieve/archive/Microsoft/small | wc -l)

#MS Pre-Count

MS4=$(ls /opt/maltrieve/archive/MS/xlarge | wc -l)
MS3=$(ls /opt/maltrieve/archive/MS/large | wc -l)
MS2=$(ls /opt/maltrieve/archive/MS/medium | wc -l)
MS1=$(ls /opt/maltrieve/archive/MS/small | wc -l)

#MS-DOS Pre-Count

MSDOS4=$(ls /opt/maltrieve/archive/MS-DOS/xlarge | wc -l)
MSDOS3=$(ls /opt/maltrieve/archive/MS-DOS/large | wc -l)
MSDOS2=$(ls /opt/maltrieve/archive/MS-DOS/medium | wc -l)
MSDOS1=$(ls /opt/maltrieve/archive/MS-DOS/small | wc -l)

#Non-ISO Pre-Count

NonISO4=$(ls /opt/maltrieve/archive/Non-ISO/xlarge | wc -l)
NonISO3=$(ls /opt/maltrieve/archive/Non-ISO/large | wc -l)
NonISO2=$(ls /opt/maltrieve/archive/Non-ISO/medium | wc -l)
NonISO1=$(ls /opt/maltrieve/archive/Non-ISO/small | wc -l)

#PalmOS Pre-Count

PalmOS4=$(ls /opt/maltrieve/archive/PalmOS/xlarge | wc -l)
PalmOS3=$(ls /opt/maltrieve/archive/PalmOS/large | wc -l)
PalmOS2=$(ls /opt/maltrieve/archive/PalmOS/medium | wc -l)
PalmOS1=$(ls /opt/maltrieve/archive/PalmOS/small | wc -l)

#PDF Pre-Count

PDF4=$(ls /opt/maltrieve/archive/PDF/xlarge | wc -l)
PDF3=$(ls /opt/maltrieve/archive/PDF/large | wc -l)
PDF2=$(ls /opt/maltrieve/archive/PDF/medium | wc -l)
PDF1=$(ls /opt/maltrieve/archive/PDF/small | wc -l)

#PE32 Pre-Count

PE324=$(ls /opt/maltrieve/archive/PE32/xlarge | wc -l)
PE323=$(ls /opt/maltrieve/archive/PE32/large | wc -l)
PE322=$(ls /opt/maltrieve/archive/PE32/medium | wc -l)
PE321=$(ls /opt/maltrieve/archive/PE32/small | wc -l)

#PE32+ Pre-Count

PE32p4=$(ls /opt/maltrieve/archive/PE32+/xlarge | wc -l)
PE32p3=$(ls /opt/maltrieve/archive/PE32+/large | wc -l)
PE32p2=$(ls /opt/maltrieve/archive/PE32+/medium | wc -l)
PE32p1=$(ls /opt/maltrieve/archive/PE32+/small | wc -l)

#PerlScript Pre-Count

PerlScript4=$(ls /opt/maltrieve/archive/PerlScript/xlarge | wc -l)
PerlScript3=$(ls /opt/maltrieve/archive/PerlScript/large | wc -l)
PerlScript2=$(ls /opt/maltrieve/archive/PerlScript/medium | wc -l)
PerlScript1=$(ls /opt/maltrieve/archive/PerlScript/small | wc -l)

#PNG Pre-Count

PNG4=$(ls /opt/maltrieve/archive/PNG/xlarge | wc -l)
PNG3=$(ls /opt/maltrieve/archive/PNG/large | wc -l)
PNG2=$(ls /opt/maltrieve/archive/PNG/medium | wc -l)
PNG1=$(ls /opt/maltrieve/archive/PNG/small | wc -l)

#POSIX Pre-Count

POSIX4=$(ls /opt/maltrieve/archive/POSIX/xlarge | wc -l)
POSIX3=$(ls /opt/maltrieve/archive/POSIX/large | wc -l)
POSIX2=$(ls /opt/maltrieve/archive/POSIX/medium | wc -l)
POSIX1=$(ls /opt/maltrieve/archive/POSIX/small | wc -l)

#RAR Pre-Count

RAR4=$(ls /opt/maltrieve/archive/RAR/xlarge | wc -l)
RAR3=$(ls /opt/maltrieve/archive/RAR/large | wc -l)
RAR2=$(ls /opt/maltrieve/archive/RAR/medium | wc -l)
RAR1=$(ls /opt/maltrieve/archive/RAR/small | wc -l)

#Ruby Pre-Count

Ruby4=$(ls /opt/maltrieve/archive/Ruby/xlarge | wc -l)
Ruby3=$(ls /opt/maltrieve/archive/Ruby/large | wc -l)
Ruby2=$(ls /opt/maltrieve/archive/Ruby/medium | wc -l)
Ruby1=$(ls /opt/maltrieve/archive/Ruby/small | wc -l)

#Symbian Pre-Count

Symbian4=$(ls /opt/maltrieve/archive/Symbian/xlarge | wc -l)
Symbian3=$(ls /opt/maltrieve/archive/Symbian/large | wc -l)
Symbian2=$(ls /opt/maltrieve/archive/Symbian/medium | wc -l)
Symbian1=$(ls /opt/maltrieve/archive/Symbian/small | wc -l)

#troff Pre-Count

troff4=$(ls /opt/maltrieve/archive/troff/xlarge | wc -l)
troff3=$(ls /opt/maltrieve/archive/troff/large | wc -l)
troff2=$(ls /opt/maltrieve/archive/troff/medium | wc -l)
troff1=$(ls /opt/maltrieve/archive/troff/small | wc -l)

#UTF8 Pre-Count

UTF84=$(ls /opt/maltrieve/archive/UTF-8/xlarge | wc -l)
UTF83=$(ls /opt/maltrieve/archive/UTF-8/large | wc -l)
UTF82=$(ls /opt/maltrieve/archive/UTF-8/medium | wc -l)
UTF81=$(ls /opt/maltrieve/archive/UTF-8/small | wc -l)

#xHTML Pre-Count

xHTML4=$(ls /opt/maltrieve/archive/xHTML/xlarge | wc -l)
xHTML3=$(ls /opt/maltrieve/archive/xHTML/large | wc -l)
xHTML2=$(ls /opt/maltrieve/archive/xHTML/medium | wc -l)
xHTML1=$(ls /opt/maltrieve/archive/xHTML/small | wc -l)

#XML Pre-Count

XML4=$(ls /opt/maltrieve/archive/XML/xlarge | wc -l)
XML3=$(ls /opt/maltrieve/archive/XML/large | wc -l)
XML2=$(ls /opt/maltrieve/archive/XML/medium | wc -l)
XML1=$(ls /opt/maltrieve/archive/XML/small | wc -l)

#Zip Pre-Count

Zip4=$(ls /opt/maltrieve/archive/Zip/xlarge | wc -l)
Zip3=$(ls /opt/maltrieve/archive/Zip/large | wc -l)
Zip2=$(ls /opt/maltrieve/archive/Zip/medium | wc -l)
Zip1=$(ls /opt/maltrieve/archive/Zip/small | wc -l)

#Now that files have been counted, we can run Maltrieve

cd /opt/maltrieve && python /opt/maltrieve/maltrieve.py 

echo Fetching Malware! This May Take Some Time...

#Total Virus Count, Post Maltrieve & Total New File Count

VariaVirus2=$(ls /opt/maltrieve/archive | wc -l)
VirusMount=$(expr $VariaVirus2 - $VariaVirus)

sleep 3
/opt/maltrieve/maltrievecategorizer.sh
echo Categorizing Malware! Please Wait...
sleep 6
echo Counting Malware... Almost Finished!
sleep 9

#Total Specific Virus Counts Before Maltrieve

#7zip Total Malware After Running Maltrieve

Szip8=$(ls /opt/maltrieve/archive/7-zip/xlarge | wc -l)
Szip7=$(ls /opt/maltrieve/archive/7-zip/large | wc -l)
Szip6=$(ls /opt/maltrieve/archive/7-zip/medium | wc -l)
Szip5=$(ls /opt/maltrieve/archive/7-zip/small | wc -l)

#7zip New Malware Calculated

Szipxl=$(expr $7zip8 - $7zip4)
Sziplg=$(expr $7zip7 - $7zip3)
Szipmd=$(expr $7zip6 - $7zip2)
Szipsm=$(expr $7zip5 - $7zip1)

#ASCII Total Malware After Running Maltrieve

ASCII8=$(ls /opt/maltrieve/archive/ASCII/xlarge | wc -l)
ASCII7=$(ls /opt/maltrieve/archive/ASCII/large | wc -l)
ASCII6=$(ls /opt/maltrieve/archive/ASCII/medium | wc -l)
ASCII5=$(ls /opt/maltrieve/archive/ASCII/small | wc -l)

#ASCII New Malware Calculated

ASCIIxl=$(expr $ASCII8 - $ASCII4)
ASCIIlg=$(expr $ASCII7 - $ASCII3)
ASCIImd=$(expr $ASCII6 - $ASCII2)
ASCIIsm=$(expr $ASCII5 - $ASCII1)

#BitTorrent Total Malware After Running Maltrieve

BitTorrent8=$(ls /opt/maltrieve/archive/BitTorrent/xlarge | wc -l)
BitTorrent7=$(ls /opt/maltrieve/archive/BitTorrent/large | wc -l)
BitTorrent6=$(ls /opt/maltrieve/archive/BitTorrent/medium | wc -l)
BitTorrent5=$(ls /opt/maltrieve/archive/BitTorrent/small | wc -l)

#BitTorrent New Malware Calculated

BitTorrentxl=$(expr $BitTorrent8 - $BitTorrent4)
BitTorrentlg=$(expr $BitTorrent7 - $BitTorrent3)
BitTorrentmd=$(expr $BitTorrent6 - $BitTorrent2)
BitTorrentsm=$(expr $BitTorrent5 - $BitTorrent1)

#bzip2 Total Malware After Running Maltrieve

bzip28=$(ls /opt/maltrieve/archive/bzip2/xlarge | wc -l)
bzip27=$(ls /opt/maltrieve/archive/bzip2/large | wc -l)
bzip26=$(ls /opt/maltrieve/archive/bzip2/medium | wc -l)
bzip25=$(ls /opt/maltrieve/archive/bzip2/small | wc -l)

#bzip2 New Malware Calculated

bzip2xl=$(expr $bzip28 - $bzip24)
bzip2lg=$(expr $bzip27 - $bzip23)
bzip2md=$(expr $bzip26 - $bzip22)
bzip2sm=$(expr $bzip25 - $bzip21)

#compiled Total Malware After Running Maltrieve

compiled8=$(ls /opt/maltrieve/archive/compiled/xlarge | wc -l)
compiled7=$(ls /opt/maltrieve/archive/compiled/large | wc -l)
compiled6=$(ls /opt/maltrieve/archive/compiled/medium | wc -l)
compiled5=$(ls /opt/maltrieve/archive/compiled/small | wc -l)

#compiled New Malware Calculated

compiledxl=$(expr $compiled8 - $compiled4)
compiledlg=$(expr $compiled7 - $compiled3)
compiledmd=$(expr $compiled6 - $compiled2)
compiledsm=$(expr $compiled5 - $compiled1)

#Composite Total Malware After Running Maltrieve

Composite8=$(ls /opt/maltrieve/archive/Composite/xlarge | wc -l)
Composite7=$(ls /opt/maltrieve/archive/Composite/large | wc -l)
Composite6=$(ls /opt/maltrieve/archive/Composite/medium | wc -l)
Composite5=$(ls /opt/maltrieve/archive/Composite/small | wc -l)

#Composite New Malware Calculated

Compositexl=$(expr $Composite8 - $Composite4)
Compositelg=$(expr $Composite7 - $Composite3)
Compositemd=$(expr $Composite6 - $Composite2)
Compositesm=$(expr $Composite5 - $Composite1)

#data Total Malware After Running Maltrieve

data8=$(ls /opt/maltrieve/archive/data/xlarge | wc -l)
data7=$(ls /opt/maltrieve/archive/data/large | wc -l)
data6=$(ls /opt/maltrieve/archive/data/medium | wc -l)
data5=$(ls /opt/maltrieve/archive/data/small | wc -l)

#data New Malware Calculated

dataxl=$(expr $data8 - $data4)
datalg=$(expr $data7 - $data3)
datamd=$(expr $data6 - $data2)
datasm=$(expr $data5 - $data1)

#Debian Total Malware After Running Maltrieve

Debian8=$(ls /opt/maltrieve/archive/Debian/xlarge | wc -l)
Debian7=$(ls /opt/maltrieve/archive/Debian/large | wc -l)
Debian6=$(ls /opt/maltrieve/archive/Debian/medium | wc -l)
Debian5=$(ls /opt/maltrieve/archive/Debian/small | wc -l)

#Debian New Malware Calculated

Debianxl=$(expr $Debian8 - $Debian4)
Debianlg=$(expr $Debian7 - $Debian3)
Debianmd=$(expr $Debian6 - $Debian2)
Debiansm=$(expr $Debian5 - $Debian1)

#Dyalog Total Malware After Running Maltrieve

Dyalog8=$(ls /opt/maltrieve/archive/Dyalog/xlarge | wc -l)
Dyalog7=$(ls /opt/maltrieve/archive/Dyalog/large | wc -l)
Dyalog6=$(ls /opt/maltrieve/archive/Dyalog/medium | wc -l)
Dyalog5=$(ls /opt/maltrieve/archive/Dyalog/small | wc -l)

#Dyalog New Malware Calculated

Dyalogxl=$(expr $Dyalog8 - $Dyalog4)
Dyaloglg=$(expr $Dyalog7 - $Dyalog3)
Dyalogmd=$(expr $Dyalog6 - $Dyalog2)
Dyalogsm=$(expr $Dyalog5 - $Dyalog1)

#ELF Total Malware After Running Maltrieve

ELF8=$(ls /opt/maltrieve/archive/ELF/xlarge | wc -l)
ELF7=$(ls /opt/maltrieve/archive/ELF/large | wc -l)
ELF6=$(ls /opt/maltrieve/archive/ELF/medium | wc -l)
ELF5=$(ls /opt/maltrieve/archive/ELF/small | wc -l)

#ELF New Malware Calculated

ELFxl=$(expr $ELF8 - $ELF4)
ELFlg=$(expr $ELF7 - $ELF3)
ELFmd=$(expr $ELF6 - $ELF2)
ELFsm=$(expr $ELF5 - $ELF1)

#Emacs Total Malware After Running Maltrieve

Emacs8=$(ls /opt/maltrieve/archive/Emacs/xlarge | wc -l)
Emacs7=$(ls /opt/maltrieve/archive/Emacs/large | wc -l)
Emacs6=$(ls /opt/maltrieve/archive/Emacs/medium | wc -l)
Emacs5=$(ls /opt/maltrieve/archive/Emacs/small | wc -l)

#Emacs New Malware Calculated

Emacsxl=$(expr $Emacs8 - $Emacs4)
Emacslg=$(expr $Emacs7 - $Emacs3)
Emacsmd=$(expr $Emacs6 - $Emacs2)
Emacssm=$(expr $Emacs5 - $Emacs1)

#exported Total Malware After Running Maltrieve

exported8=$(ls /opt/maltrieve/archive/exported/xlarge | wc -l)
exported7=$(ls /opt/maltrieve/archive/exported/large | wc -l)
exported6=$(ls /opt/maltrieve/archive/exported/medium | wc -l)
exported5=$(ls /opt/maltrieve/archive/exported/small | wc -l)

#exported New Malware Calculated

exportedxl=$(expr $exported8 - $exported4)
exportedlg=$(expr $exported7 - $exported3)
exportedmd=$(expr $exported6 - $exported2)
exportedsm=$(expr $exported5 - $exported1)

#GIF Total Malware After Running Maltrieve

GIF8=$(ls /opt/maltrieve/archive/GIF/xlarge | wc -l)
GIF7=$(ls /opt/maltrieve/archive/GIF/large | wc -l)
GIF6=$(ls /opt/maltrieve/archive/GIF/medium | wc -l)
GIF5=$(ls /opt/maltrieve/archive/GIF/small | wc -l)

#GIF New Malware Calculated

GIFxl=$(expr $GIF8 - $GIF4)
GIFlg=$(expr $GIF7 - $GIF3)
GIFmd=$(expr $GIF6 - $GIF2)
GIFsm=$(expr $GIF5 - $GIF1)

#HTML Total Malware After Running Maltrieve

HTML8=$(ls /opt/maltrieve/archive/HTML/xlarge | wc -l)
HTML7=$(ls /opt/maltrieve/archive/HTML/large | wc -l)
HTML6=$(ls /opt/maltrieve/archive/HTML/medium | wc -l)
HTML5=$(ls /opt/maltrieve/archive/HTML/small | wc -l)

#HTML New Malware Calculated

HTMLxl=$(expr $HTML8 - $HTML4)
HTMLlg=$(expr $HTML7 - $HTML3)
HTMLmd=$(expr $HTML6 - $HTML2)
HTMLsm=$(expr $HTML5 - $HTML1)

#ISO Total Malware After Running Maltrieve

ISO8=$(ls /opt/maltrieve/archive/ISO/xlarge | wc -l)
ISO7=$(ls /opt/maltrieve/archive/ISO/large | wc -l)
ISO6=$(ls /opt/maltrieve/archive/ISO/medium | wc -l)
ISO5=$(ls /opt/maltrieve/archive/ISO/small | wc -l)

#ISO New Malware Calculated

ISOxl=$(expr $ISO8 - $ISO4)
ISOlg=$(expr $ISO7 - $ISO3)
ISOmd=$(expr $ISO6 - $ISO2)
ISOsm=$(expr $ISO5 - $ISO1)

#ISO8859 Total Malware After Running Maltrieve

ISO88598=$(ls /opt/maltrieve/archive/ISO-8859/xlarge | wc -l)
ISO88597=$(ls /opt/maltrieve/archive/ISO-8859/large | wc -l)
ISO88596=$(ls /opt/maltrieve/archive/ISO-8859/medium | wc -l)
ISO88595=$(ls /opt/maltrieve/archive/ISO-8859/small | wc -l)

#ISO8859 New Malware Calculated

ISO8859xl=$(expr $ISO88598 - $ISO88594)
ISO8859lg=$(expr $ISO88597 - $ISO88593)
ISO8859md=$(expr $ISO88596 - $ISO88592)
ISO8859sm=$(expr $ISO88595 - $ISO88591)

#Java Total Malware After Running Maltrieve

Java8=$(ls /opt/maltrieve/archive/Java/xlarge | wc -l)
Java7=$(ls /opt/maltrieve/archive/Java/large | wc -l)
Java6=$(ls /opt/maltrieve/archive/Java/medium | wc -l)
Java5=$(ls /opt/maltrieve/archive/Java/small | wc -l)

#Java New Malware Calculated

Javaxl=$(expr $Java8 - $Java4)
Javalg=$(expr $Java7 - $Java3)
Javamd=$(expr $Java6 - $Java2)
Javasm=$(expr $Java5 - $Java1)

#JPEG Total Malware After Running Maltrieve

JPEG8=$(ls /opt/maltrieve/archive/JPEG/xlarge | wc -l)
JPEG7=$(ls /opt/maltrieve/archive/JPEG/large | wc -l)
JPEG6=$(ls /opt/maltrieve/archive/JPEG/medium | wc -l)
JPEG5=$(ls /opt/maltrieve/archive/JPEG/small | wc -l)

#JPEG New Malware Calculated

JPEGxl=$(expr $JPEG8 - $JPEG4)
JPEGlg=$(expr $JPEG7 - $JPEG3)
JPEGmd=$(expr $JPEG6 - $JPEG2)
JPEGsm=$(expr $JPEG5 - $JPEG1)

#Lha Total Malware After Running Maltrieve

Lha8=$(ls /opt/maltrieve/archive/Lha/xlarge | wc -l)
Lha7=$(ls /opt/maltrieve/archive/Lha/large | wc -l)
Lha6=$(ls /opt/maltrieve/archive/Lha/medium | wc -l)
Lha5=$(ls /opt/maltrieve/archive/Lha/small | wc -l)

#Lha New Malware Calculated

Lhaxl=$(expr $Lha8 - $Lha4)
Lhalg=$(expr $Lha7 - $Lha3)
Lhamd=$(expr $Lha6 - $Lha2)
Lhasm=$(expr $Lha5 - $Lha1)

#Littleendian Total Malware After Running Maltrieve

Littleendian8=$(ls /opt/maltrieve/archive/Littleendian/xlarge | wc -l)
Littleendian7=$(ls /opt/maltrieve/archive/Littleendian/large | wc -l)
Littleendian6=$(ls /opt/maltrieve/archive/Littleendian/medium | wc -l)
Littleendian5=$(ls /opt/maltrieve/archive/Littleendian/small | wc -l)

#Littleendian New Malware Calculated

Littleendianxl=$(expr $Littleendian8 - $Littleendian4)
Littleendianlg=$(expr $Littleendian7 - $Littleendian3)
Littleendianmd=$(expr $Littleendian6 - $Littleendian2)
Littleendiansm=$(expr $Littleendian5 - $Littleendian1)

#Macintosh Total Malware After Running Maltrieve

Macintosh8=$(ls /opt/maltrieve/archive/Macintosh/xlarge | wc -l)
Macintosh7=$(ls /opt/maltrieve/archive/Macintosh/large | wc -l)
Macintosh6=$(ls /opt/maltrieve/archive/Macintosh/medium | wc -l)
Macintosh5=$(ls /opt/maltrieve/archive/Macintosh/small | wc -l)

#Macintosh New Malware Calculated

Macintoshxl=$(expr $Macintosh8 - $Macintosh4)
Macintoshlg=$(expr $Macintosh7 - $Macintosh3)
Macintoshmd=$(expr $Macintosh6 - $Macintosh2)
Macintoshsm=$(expr $Macintosh5 - $Macintosh1)

#Macromedia Total Malware After Running Maltrieve

Macromedia8=$(ls /opt/maltrieve/archive/Macromedia/xlarge | wc -l)
Macromedia7=$(ls /opt/maltrieve/archive/Macromedia/large | wc -l)
Macromedia6=$(ls /opt/maltrieve/archive/Macromedia/medium | wc -l)
Macromedia5=$(ls /opt/maltrieve/archive/Macromedia/small | wc -l)

#Macromedia New Malware Calculated

Macromediaxl=$(expr $Macromedia8 - $Macromedia4)
Macromedialg=$(expr $Macromedia7 - $Macromedia3)
Macromediamd=$(expr $Macromedia6 - $Macromedia2)
Macromediasm=$(expr $Macromedia5 - $Macromedia1)

#Microsoft Total Malware After Running Maltrieve

Microsoft8=$(ls /opt/maltrieve/archive/Microsoft/xlarge | wc -l)
Microsoft7=$(ls /opt/maltrieve/archive/Microsoft/large | wc -l)
Microsoft6=$(ls /opt/maltrieve/archive/Microsoft/medium | wc -l)
Microsoft5=$(ls /opt/maltrieve/archive/Microsoft/small | wc -l)

#Microsoft New Malware Calculated

Microsoftxl=$(expr $Microsoft8 - $Microsoft4)
Microsoftlg=$(expr $Microsoft7 - $Microsoft3)
Microsoftmd=$(expr $Microsoft6 - $Microsoft2)
Microsoftsm=$(expr $Microsoft5 - $Microsoft1)

#MS Total Malware After Running Maltrieve

MS8=$(ls /opt/maltrieve/archive/MS/xlarge | wc -l)
MS7=$(ls /opt/maltrieve/archive/MS/large | wc -l)
MS6=$(ls /opt/maltrieve/archive/MS/medium | wc -l)
MS5=$(ls /opt/maltrieve/archive/MS/small | wc -l)

#MS New Malware Calculated

MSxl=$(expr $MS8 - $MS4)
MSlg=$(expr $MS7 - $MS3)
MSmd=$(expr $MS6 - $MS2)
MSsm=$(expr $MS5 - $MS1)

#MSDOS Total Malware After Running Maltrieve

MSDOS8=$(ls /opt/maltrieve/archive/MS-DOS/xlarge | wc -l)
MSDOS7=$(ls /opt/maltrieve/archive/MS-DOS/large | wc -l)
MSDOS6=$(ls /opt/maltrieve/archive/MS-DOS/medium | wc -l)
MSDOS5=$(ls /opt/maltrieve/archive/MS-DOS/small | wc -l)

#MSDOS New Malware Calculated

MSDOSxl=$(expr $MSDOS8 - $MSDOS4)
MSDOSlg=$(expr $MSDOS7 - $MSDOS3)
MSDOSmd=$(expr $MSDOS6 - $MSDOS2)
MSDOSsm=$(expr $MSDOS5 - $MSDOS1)

#NonISO Total Malware After Running Maltrieve

NonISO8=$(ls /opt/maltrieve/archive/Non-ISO/xlarge | wc -l)
NonISO7=$(ls /opt/maltrieve/archive/Non-ISO/large | wc -l)
NonISO6=$(ls /opt/maltrieve/archive/Non-ISO/medium | wc -l)
NonISO5=$(ls /opt/maltrieve/archive/Non-ISO/small | wc -l)

#NonISO New Malware Calculated

NonISOxl=$(expr $NonISO8 - $NonISO4)
NonISOlg=$(expr $NonISO7 - $NonISO3)
NonISOmd=$(expr $NonISO6 - $NonISO2)
NonISOsm=$(expr $NonISO5 - $NonISO1)

#PalmOS Total Malware After Running Maltrieve

PalmOS8=$(ls /opt/maltrieve/archive/PalmOS/xlarge | wc -l)
PalmOS7=$(ls /opt/maltrieve/archive/PalmOS/large | wc -l)
PalmOS6=$(ls /opt/maltrieve/archive/PalmOS/medium | wc -l)
PalmOS5=$(ls /opt/maltrieve/archive/PalmOS/small | wc -l)

#PalmOS New Malware Calculated

PalmOSxl=$(expr $PalmOS8 - $PalmOS4)
PalmOSlg=$(expr $PalmOS7 - $PalmOS3)
PalmOSmd=$(expr $PalmOS6 - $PalmOS2)
PalmOSsm=$(expr $PalmOS5 - $PalmOS1)

#PDF Total Malware After Running Maltrieve

PDF8=$(ls /opt/maltrieve/archive/PDF/xlarge | wc -l)
PDF7=$(ls /opt/maltrieve/archive/PDF/large | wc -l)
PDF6=$(ls /opt/maltrieve/archive/PDF/medium | wc -l)
PDF5=$(ls /opt/maltrieve/archive/PDF/small | wc -l)

#PDF New Malware Calculated

PDFxl=$(expr $PDF8 - $PDF4)
PDFlg=$(expr $PDF7 - $PDF3)
PDFmd=$(expr $PDF6 - $PDF2)
PDFsm=$(expr $PDF5 - $PDF1)

#PE32 Total Malware After Running Maltrieve

PE328=$(ls /opt/maltrieve/archive/PE32/xlarge | wc -l)
PE327=$(ls /opt/maltrieve/archive/PE32/large | wc -l)
PE326=$(ls /opt/maltrieve/archive/PE32/medium | wc -l)
PE325=$(ls /opt/maltrieve/archive/PE32/small | wc -l)

#PE32 New Malware Calculated

PE32xl=$(expr $PE328 - $PE324)
PE32lg=$(expr $PE327 - $PE323)
PE32md=$(expr $PE326 - $PE322)
PE32sm=$(expr $PE325 - $PE321)

#PE32+ Total Malware After Running Maltrieve

PE32p8=$(ls /opt/maltrieve/archive/PE32+/xlarge | wc -l)
PE32p7=$(ls /opt/maltrieve/archive/PE32+/large | wc -l)
PE32p6=$(ls /opt/maltrieve/archive/PE32+/medium | wc -l)
PE32p5=$(ls /opt/maltrieve/archive/PE32+/small | wc -l)

#PE32+ New Malware Calculated

PE32pxl=$(expr $PE32p8 - $PE32p4)
PE32plg=$(expr $PE32p7 - $PE32p3)
PE32pmd=$(expr $PE32p6 - $PE32p2)
PE32psm=$(expr $PE32p5 - $PE32p1)

#PerlScript Total Malware After Running Maltrieve

PerlScript8=$(ls /opt/maltrieve/archive/PerlScript/xlarge | wc -l)
PerlScript7=$(ls /opt/maltrieve/archive/PerlScript/large | wc -l)
PerlScript6=$(ls /opt/maltrieve/archive/PerlScript/medium | wc -l)
PerlScript5=$(ls /opt/maltrieve/archive/PerlScript/small | wc -l)

#PerlScript New Malware Calculated

PerlScriptxl=$(expr $PerlScript8 - $PerlScript4)
PerlScriptlg=$(expr $PerlScript7 - $PerlScript3)
PerlScriptmd=$(expr $PerlScript6 - $PerlScript2)
PerlScriptsm=$(expr $PerlScript5 - $PerlScript1)

#PNG Total Malware After Running Maltrieve

PNG8=$(ls /opt/maltrieve/archive/PNG/xlarge | wc -l)
PNG7=$(ls /opt/maltrieve/archive/PNG/large | wc -l)
PNG6=$(ls /opt/maltrieve/archive/PNG/medium | wc -l)
PNG5=$(ls /opt/maltrieve/archive/PNG/small | wc -l)

#PNG New Malware Calculated

PNGxl=$(expr $PNG8 - $PNG4)
PNGlg=$(expr $PNG7 - $PNG3)
PNGmd=$(expr $PNG6 - $PNG2)
PNGsm=$(expr $PNG5 - $PNG1)

#POSIX Total Malware After Running Maltrieve

POSIX8=$(ls /opt/maltrieve/archive/POSIX/xlarge | wc -l)
POSIX7=$(ls /opt/maltrieve/archive/POSIX/large | wc -l)
POSIX6=$(ls /opt/maltrieve/archive/POSIX/medium | wc -l)
POSIX5=$(ls /opt/maltrieve/archive/POSIX/small | wc -l)

#POSIX New Malware Calculated

POSIXxl=$(expr $POSIX8 - $POSIX4)
POSIXlg=$(expr $POSIX7 - $POSIX3)
POSIXmd=$(expr $POSIX6 - $POSIX2)
POSIXsm=$(expr $POSIX5 - $POSIX1)

#RAR Total Malware After Running Maltrieve

RAR8=$(ls /opt/maltrieve/archive/RAR/xlarge | wc -l)
RAR7=$(ls /opt/maltrieve/archive/RAR/large | wc -l)
RAR6=$(ls /opt/maltrieve/archive/RAR/medium | wc -l)
RAR5=$(ls /opt/maltrieve/archive/RAR/small | wc -l)

#RAR New Malware Calculated

RARxl=$(expr $RAR8 - $RAR4)
RARlg=$(expr $RAR7 - $RAR3)
RARmd=$(expr $RAR6 - $RAR2)
RARsm=$(expr $RAR5 - $RAR1)

#Ruby Total Malware After Running Maltrieve

Ruby8=$(ls /opt/maltrieve/archive/Ruby/xlarge | wc -l)
Ruby7=$(ls /opt/maltrieve/archive/Ruby/large | wc -l)
Ruby6=$(ls /opt/maltrieve/archive/Ruby/medium | wc -l)
Ruby5=$(ls /opt/maltrieve/archive/Ruby/small | wc -l)

#Ruby New Malware Calculated

Rubyxl=$(expr $Ruby8 - $Ruby4)
Rubylg=$(expr $Ruby7 - $Ruby3)
Rubymd=$(expr $Ruby6 - $Ruby2)
Rubysm=$(expr $Ruby5 - $Ruby1)

#Symbian Total Malware After Running Maltrieve

Symbian8=$(ls /opt/maltrieve/archive/Symbian/xlarge | wc -l)
Symbian7=$(ls /opt/maltrieve/archive/Symbian/large | wc -l)
Symbian6=$(ls /opt/maltrieve/archive/Symbian/medium | wc -l)
Symbian5=$(ls /opt/maltrieve/archive/Symbian/small | wc -l)

#Symbian New Malware Calculated

Symbianxl=$(expr $Symbian8 - $Symbian4)
Symbianlg=$(expr $Symbian7 - $Symbian3)
Symbianmd=$(expr $Symbian6 - $Symbian2)
Symbiansm=$(expr $Symbian5 - $Symbian1)

#troff Total Malware After Running Maltrieve

troff8=$(ls /opt/maltrieve/archive/troff/xlarge | wc -l)
troff7=$(ls /opt/maltrieve/archive/troff/large | wc -l)
troff6=$(ls /opt/maltrieve/archive/troff/medium | wc -l)
troff5=$(ls /opt/maltrieve/archive/troff/small | wc -l)

#troff New Malware Calculated

troffxl=$(expr $troff8 - $troff4)
trofflg=$(expr $troff7 - $troff3)
troffmd=$(expr $troff6 - $troff2)
troffsm=$(expr $troff5 - $troff1)

#UTF8 Total Malware After Running Maltrieve

UTF88=$(ls /opt/maltrieve/archive/UTF-8/xlarge | wc -l)
UTF87=$(ls /opt/maltrieve/archive/UTF-8/large | wc -l)
UTF86=$(ls /opt/maltrieve/archive/UTF-8/medium | wc -l)
UTF85=$(ls /opt/maltrieve/archive/UTF-8/small | wc -l)

#UTF8 New Malware Calculated

UTF8xl=$(expr $UTF88 - $UTF84)
UTF8lg=$(expr $UTF87 - $UTF83)
UTF8md=$(expr $UTF86 - $UTF82)
UTF8sm=$(expr $UTF85 - $UTF81)

#xHTML Total Malware After Running Maltrieve

xHTML8=$(ls /opt/maltrieve/archive/xHTML/xlarge | wc -l)
xHTML7=$(ls /opt/maltrieve/archive/xHTML/large | wc -l)
xHTML6=$(ls /opt/maltrieve/archive/xHTML/medium | wc -l)
xHTML5=$(ls /opt/maltrieve/archive/xHTML/small | wc -l)

#xHTML New Malware Calculated

xHTMLxl=$(expr $xHTML8 - $xHTML4)
xHTMLlg=$(expr $xHTML7 - $xHTML3)
xHTMLmd=$(expr $xHTML6 - $xHTML2)
xHTMLsm=$(expr $xHTML5 - $xHTML1)

#XML Total Malware After Running Maltrieve

XML8=$(ls /opt/maltrieve/archive/XML/xlarge | wc -l)
XML7=$(ls /opt/maltrieve/archive/XML/large | wc -l)
XML6=$(ls /opt/maltrieve/archive/XML/medium | wc -l)
XML5=$(ls /opt/maltrieve/archive/XML/small | wc -l)

#XML New Malware Calculated

XMLxl=$(expr $XML8 - $XML4)
XMLlg=$(expr $XML7 - $XML3)
XMLmd=$(expr $XML6 - $XML2)
XMLsm=$(expr $XML5 - $XML1)

#Zip Total Malware After Running Maltrieve

Zip8=$(ls /opt/maltrieve/archive/Zip/xlarge | wc -l)
Zip7=$(ls /opt/maltrieve/archive/Zip/large | wc -l)
Zip6=$(ls /opt/maltrieve/archive/Zip/medium | wc -l)
Zip5=$(ls /opt/maltrieve/archive/Zip/small | wc -l)

#Zip New Malware Calculated

Zipxl=$(expr $Zip8 - $Zip4)
Ziplg=$(expr $Zip7 - $Zip3)
Zipmd=$(expr $Zip6 - $Zip2)
Zipsm=$(expr $Zip5 - $Zip1)

echo
echo $VirusMount Malware Downloaded 
echo
echo $VirusMount Malware Downloaded $(date) >> /opt/maltrieve/Malcounted
echo >> /opt/maltrieve/Malcounted
echo Note: Some Malware Downloaded May Have Already Existed In Archives
echo Note: Some Malware Downloaded May Have Already Existed In Archives >> /opt/maltrieve/Malcounted
echo Note: If A New Category Of Malware Was Downloaded, It Has Not Been Listed Below.
echo Note: If A New Category Of Malware Was Downloaded, It Has Not Been Listed Below. >> /opt/maltrieve/Malcounted
echo
echo >> /opt/maltrieve/Malcounted
echo 7zip Extra Large: $Szipxl Large: $Sziplg Medium: $Szipmd Small: $Szipsm 
echo 7zip Extra Large: $Szipxl Large: $Sziplg Medium: $Szipmd Small: $Szipsm >> /opt/maltrieve/Malcounted
echo ASCII Extra Large: $ASCIIxl Large: $ASCIIlg Medium: $ASCIImd Small: $ASCIIsm 
echo ASCII Extra Large: $ASCIIxl Large: $ASCIIlg Medium: $ASCIImd Small: $ASCIIsm >> /opt/maltrieve/Malcounted
echo BitTorrent Extra Large: $BitTorrentxl Large: $BitTorrentlg Medium: $BitTorrentmd Small: $BitTorrentsm 
echo BitTorrent Extra Large: $BitTorrentxl Large: $BitTorrentlg Medium: $BitTorrentmd Small: $BitTorrentsm >> /opt/maltrieve/Malcounted
echo bzip2 Extra Large: $bzip2xl Large: $bzip2lg Medium: $bzip2md Small: $bzip2sm 
echo bzip2 Extra Large: $bzip2xl Large: $bzip2lg Medium: $bzip2md Small: $bzip2sm >> /opt/maltrieve/Malcounted
echo compiled Extra Large: $compiledxl Large: $compiledlg Medium: $compiledmd Small: $compiledsm 
echo compiled Extra Large: $compiledxl Large: $compiledlg Medium: $compiledmd Small: $compiledsm >> /opt/maltrieve/Malcounted
echo Composite Extra Large: $Compositexl Large: $Compositelg Medium: $Compositemd Small: $Compositesm 
echo Composite Extra Large: $Compositexl Large: $Compositelg Medium: $Compositemd Small: $Compositesm >> /opt/maltrieve/Malcounted
echo data Extra Large: $dataxl Large: $datalg Medium: $datamd Small: $datasm 
echo data Extra Large: $dataxl Large: $datalg Medium: $datamd Small: $datasm >> /opt/maltrieve/Malcounted
echo Debian Extra Large: $Debianxl Large: $Debianlg Medium: $Debianmd Small: $Debiansm 
echo Debian Extra Large: $Debianxl Large: $Debianlg Medium: $Debianmd Small: $Debiansm >> /opt/maltrieve/Malcounted
echo Dyalog Extra Large: $Dyalogxl Large: $Dyaloglg Medium: $Dyalogmd Small: $Dyalogsm 
echo Dyalog Extra Large: $Dyalogxl Large: $Dyaloglg Medium: $Dyalogmd Small: $Dyalogsm >> /opt/maltrieve/Malcounted
echo ELF Extra Large: $ELFxl Large: $ELFlg Medium: $ELFmd Small: $ELFsm 
echo ELF Extra Large: $ELFxl Large: $ELFlg Medium: $ELFmd Small: $ELFsm >> /opt/maltrieve/Malcounted
echo Emacs Extra Large: $Emacsxl Large: $Emacslg Medium: $Emacsmd Small: $Emacssm 
echo Emacs Extra Large: $Emacsxl Large: $Emacslg Medium: $Emacsmd Small: $Emacssm >> /opt/maltrieve/Malcounted
echo exported Extra Large: $exportedxl Large: $exportedlg Medium: $exportedmd Small: $exportedsm 
echo exported Extra Large: $exportedxl Large: $exportedlg Medium: $exportedmd Small: $exportedsm >> /opt/maltrieve/Malcounted
echo GIF Extra Large: $GIFxl Large: $GIFlg Medium: $GIFmd Small: $GIFsm 
echo GIF Extra Large: $GIFxl Large: $GIFlg Medium: $GIFmd Small: $GIFsm >> /opt/maltrieve/Malcounted
echo HTML Extra Large: $HTMLxl Large: $HTMLlg Medium: $HTMLmd Small: $HTMLsm
echo HTML Extra Large: $HTMLxl Large: $HTMLlg Medium: $HTMLmd Small: $HTMLsm >> /opt/maltrieve/Malcounted
echo ISO8859 Extra Large: $ISO8859xl Large: $ISO8859lg Medium: $ISO8859md Small: $ISO8859sm 
echo ISO8859 Extra Large: $ISO8859xl Large: $ISO8859lg Medium: $ISO8859md Small: $ISO8859sm >> /opt/maltrieve/Malcounted
echo ISO Extra Large: $ISOxl Large: $ISOlg Medium: $ISOmd Small: $ISOsm 
echo ISO Extra Large: $ISOxl Large: $ISOlg Medium: $ISOmd Small: $ISOsm >> /opt/maltrieve/Malcounted
echo Java Extra Large: $Javaxl Large: $Javalg Medium: $Javamd Small: $Javasm 
echo Java Extra Large: $Javaxl Large: $Javalg Medium: $Javamd Small: $Javasm >> /opt/maltrieve/Malcounted
echo JPEG Extra Large: $JPEGxl Large: $JPEGlg Medium: $JPEGmd Small: $JPEGsm 
echo JPEG Extra Large: $JPEGxl Large: $JPEGlg Medium: $JPEGmd Small: $JPEGsm >> /opt/maltrieve/Malcounted
echo Lha Extra Large: $Lhaxl Large: $Lhalg Medium: $Lhamd Small: $Lhasm 
echo Lha Extra Large: $Lhaxl Large: $Lhalg Medium: $Lhamd Small: $Lhasm >> /opt/maltrieve/Malcounted
echo Littleendian Extra Large: $Littleendianxl Large: $Littleendianlg Medium: $Littleendianmd Small: $Littleendiansm 
echo Littleendian Extra Large: $Littleendianxl Large: $Littleendianlg Medium: $Littleendianmd Small: $Littleendiansm >> /opt/maltrieve/Malcounted
echo Macintosh Extra Large: $Macintoshxl Large: $Macintoshlg Medium: $Macintoshmd Small: $Macintoshsm 
echo Macintosh Extra Large: $Macintoshxl Large: $Macintoshlg Medium: $Macintoshmd Small: $Macintoshsm >> /opt/maltrieve/Malcounted
echo Macromedia Extra Large: $Macromediaxl Large: $Macromedialg Medium: $Macromediamd Small: $Macromediasm
echo Macromedia Extra Large: $Macromediaxl Large: $Macromedialg Medium: $Macromediamd Small: $Macromediasm >> /opt/maltrieve/Malcounted
echo Microsoft Extra Large: $Microsoftxl Large: $Microsoftlg Medium: $Microsoftmd Small: $Microsoftsm 
echo Microsoft Extra Large: $Microsoftxl Large: $Microsoftlg Medium: $Microsoftmd Small: $Microsoftsm >> /opt/maltrieve/Malcounted
echo MS Extra Large: $MSxl Large: $MSlg Medium: $MSmd Small: $MSsm 
echo MS Extra Large: $MSxl Large: $MSlg Medium: $MSmd Small: $MSsm  >> /opt/maltrieve/Malcounted
echo MSDOS Extra Large: $MSDOSxl Large: $MSDOSlg Medium: $MSDOSmd Small: $MSDOSsm 
echo MSDOS Extra Large: $MSDOSxl Large: $MSDOSlg Medium: $MSDOSmd Small: $MSDOSsm  >> /opt/maltrieve/Malcounted
echo NonISO Extra Large: $NonISOxl Large: $NonISOlg Medium: $NonISOmd Small: $NonISOsm 
echo NonISO Extra Large: $NonISOxl Large: $NonISOlg Medium: $NonISOmd Small: $NonISOsm >> /opt/maltrieve/Malcounted
echo PalmOS Extra Large: $PalmOSxl Large: $PalmOSlg Medium: $PalmOSmd Small: $PalmOSsm 
echo PalmOS Extra Large: $PalmOSxl Large: $PalmOSlg Medium: $PalmOSmd Small: $PalmOSsm >> /opt/maltrieve/Malcounted
echo PDF Extra Large: $PDFxl Large: $PDFlg Medium: $PDFmd Small: $PDFsm 
echo PDF Extra Large: $PDFxl Large: $PDFlg Medium: $PDFmd Small: $PDFsm >> /opt/maltrieve/Malcounted
echo PE32 Extra Large: $PE32xl Large: $PE32lg Medium: $PE32md Small: $PE32sm 
echo PE32 Extra Large: $PE32xl Large: $PE32lg Medium: $PE32md Small: $PE32sm >> /opt/maltrieve/Malcounted
echo PE32p Extra Large: $PE32pxl Large: $PE32plg Medium: $PE32pmd Small: $PE32psm 
echo PE32p Extra Large: $PE32pxl Large: $PE32plg Medium: $PE32pmd Small: $PE32psm >> /opt/maltrieve/Malcounted
echo PerlScript Extra Large: $PerlScriptxl Large: $PerlScriptlg Medium: $PerlScriptmd Small $PerlScriptsm
echo PerlScript Extra Large: $PerlScriptxl Large: $PerlScriptlg Medium: $PerlScriptmd Small $PerlScriptsm >> /opt/maltrieve/Malcounted
echo PNG Extra Large: $PNGxl Large: $PNGlg Medium: $PNGmd Small: $PNGsm 
echo PNG Extra Large: $PNGxl Large: $PNGlg Medium: $PNGmd Small: $PNGsm >> /opt/maltrieve/Malcounted
echo POSIX Extra Large: $POSIXxl Large: $POSIXlg Medium: $POSIXmd Small: $POSIXsm 
echo POSIX Extra Large: $POSIXxl Large: $POSIXlg Medium: $POSIXmd Small: $POSIXsm >> /opt/maltrieve/Malcounted
echo RAR Extra Large: $RARxl Large: $RARlg Medium: $RARmd Small: $RARsm 
echo RAR Extra Large: $RARxl Large: $RARlg Medium: $RARmd Small: $RARsm >> /opt/maltrieve/Malcounted
echo Ruby Extra Large: $Rubyxl Large: $Rubylg Medium: $Rubymd Small: $Rubysm 
echo Ruby Extra Large: $Rubyxl Large: $Rubylg Medium: $Rubymd Small: $Rubysm >> /opt/maltrieve/Malcounted
echo Symbian Extra Large: $Symbianxl Large: $Symbianlg Medium: $Symbianmd Small: $Symbiansm 
echo Symbian Extra Large: $Symbianxl Large: $Symbianlg Medium: $Symbianmd Small: $Symbiansm >> /opt/maltrieve/Malcounted
echo troff Extra Large: $troffxl Large: $trofflg Medium: $troffmd Small: $troffsm 
echo troff Extra Large: $troffxl Large: $trofflg Medium: $troffmd Small: $troffsm >> /opt/maltrieve/Malcounted
echo UTF8 Extra Large: $UTF8xl Large: $UTF8lg Medium: $UTF8md Small: $UTF8sm 
echo UTF8 Extra Large: $UTF8xl Large: $UTF8lg Medium: $UTF8md Small: $UTF8sm >> /opt/maltrieve/Malcounted
echo xHTML Extra Large: $xHTMLxl Large: $xHTMLlg Medium: $xHTMLmd Small: $xHTMLsm 
echo xHTML Extra Large: $xHTMLxl Large: $xHTMLlg Medium: $xHTMLmd Small: $xHTMLsm >> /opt/maltrieve/Malcounted
echo XML Extra Large: $XMLxl Large: $XMLlg Medium: $XMLmd Small: $XMLsm 
echo XML Extra Large: $XMLxl Large: $XMLlg Medium: $XMLmd Small: $XMLsm >> /opt/maltrieve/Malcounted
echo Zip Extra Large: $Zipxl Large: $Ziplg Medium: $Zipmd Small: $Zipsm 
echo Zip Extra Large: $Zipxl Large: $Ziplg Medium: $Zipmd Small: $Zipsm >> /opt/maltrieve/Malcounted
echo  >> /opt/maltrieve/Malcounted
echo
echo Thank You For Running Maltrieve! 
echo ................................
echo Thank You For Running Maltrieve! >> /opt/maltrieve/Malcounted
echo ................................ >> /opt/maltrieve/Malcounted
echo
